# What is PyTorch?
Open source Machine learning and deep learning framework.  
A **framework** is pre-built structure or set of tools that helps you build applications faster and more efficiently by handling common tasks for you.


**NOTE:-**  
There is another major deep learning framework called TensorFlow (developed by google).    
PyTorch developed by Meta (facebook) is generally preferred in research for its simplicity and flexibility. Therefore, we'll be using PyTorch.

## Is it necessary to use PyTorch for deep learning and machine learning tasks?

No, everything can be done manually, but it's:
- Time-consuming
- Hard to scale
- Risk of bugs in math-heavy code

With PyTorch there are many adavantages like : -
- Automatic differentiation (autograd)
- Easy GPU acceleration
- Built-in dataset/dataloader tools
- $\dots$
- $\dots$, etc.

Therefore, PyTorch is preferred.

# Introduction to tensors

**Tensors:** Data structures similar to NumPy arrays but with extra features like GPU Acceleration, Automatic Differentiation (Autograd), etc.  
**Fundamental building blocks of machine learning**.


In [ ]:
# Creating tensors

import torch

## Scaler
tensor1= torch.tensor(3)
print (f'tensor1: {tensor1.item()}, its dimensions: {tensor1.ndim}') # item() give raw value (not tensor), works only with one-element tensors
print(type(tensor1), type (tensor1.item()))

## Vector
tensor2= torch.tensor([3,4])
print(f'tensor2: {tensor2}, Dimension: {tensor2.ndim}, Shape: {tensor2.shape}')

## Similarly higher dimensional tensors can be made....


tensor1: 3, its dimensions: 0
<class 'torch.Tensor'> <class 'int'>
tensor2: tensor([3, 4]), Dimension: 1, Shape: torch.Size([2])


In [ ]:
# Creating random tensors

rand1= torch.rand(size=(2,3)) # Write the shape of tensor you want
print(rand1)

## For reproducibility
import random
torch.manual_seed(42)
rand2= torch.rand(size=(2,3))
print(rand2)

# Zeros and ones

zeros= torch.zeros(size=(2,3))
ones= torch.ones(size=(2,3))
print(zeros)
print(ones)

# With a Range of number

one_to_five= torch.arange(1,6,1) # (start, stop, step)
print(one_to_five)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([1, 2, 3, 4, 5])


# Basic Operation on tensors

In [75]:
## Addition
tensor1= torch.tensor([1,2,3,4,5])
added= tensor1 +10 ## Addition
print(tensor1)
print(added)

## Subtraction 
sub= tensor1 - 5 
print(sub)

## Similary Multiplication & division......

## Matric multiplication
torch.matmul(tensor1, tensor1) # or tensor1 @ tensor1

## Transpose
tensor_x= torch.tensor([[1,2,3],[4,5,6]])

tensor_x, tensor_x.T

tensor([1, 2, 3, 4, 5])
tensor([11, 12, 13, 14, 15])
tensor([-4, -3, -2, -1,  0])


(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[1, 4],
         [2, 5],
         [3, 6]]))

# Datatype :-


There are different tensor datatypes like float32, float64, etc. It is important to keep the datasets of the tensors you are dealing with in mind or it can lead to errors (dtype dont match) if not handelled correctly.

**Most common issues (that we might come across while making models) : -**  
Dtype mismatches, shape mismatches or not on the same device.

In [ ]:
print(tensor2)
print(f'Dtype: {tensor2.dtype}') # Datatype
print(f'Device: {tensor2.device}') # Device: where the tensor is stored
print(f'Shape: {tensor2.shape}') # Shape of the tensor



tensor([3, 4])
Dtype: torch.int64
Device: cpu
Shape: torch.Size([2])


In [ ]:
# Changing Datatypes

## Changing Datatype
print(tensor2.dtype)
tensor3= tensor2.type(torch.float32)
print(tensor2.dtype, tensor3.dtype)

## Changing Shape

# Reshaping

torch.int64
torch.int64 torch.float32


In [42]:
# Changing Shapes

## Reshaping
tensor4= torch.arange(0,10,1)
print(tensor4, tensor4.shape)

tensor5= tensor4.reshape(2,5)
print(tensor5, tensor5.shape)

tensor6= tensor4.view(2,5)   # view() shares the same memory as the original tensor, so changing the new tensor can change the original tensor
print(tensor6, tensor6.shape)

## Stacking
tensor7= torch.stack([tensor4, tensor4])
print(tensor7)

## Unsqueezing
tensor8= tensor6.unsqueeze(dim=0) # Add 1 dimension at a specific index
print(tensor6.shape, tensor8.shape)

## Squeezing 
tensor9= tensor8.squeeze() # removes 1 valued dimensions
tensor8.shape, tensor9.shape




tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([10])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]) torch.Size([2, 5])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]) torch.Size([2, 5])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([2, 5]) torch.Size([1, 2, 5])


(torch.Size([1, 2, 5]), torch.Size([2, 5]))

In [ ]:
# Changing Device (in which it is stored)

if torch.cuda.is_available() is True:
    device= "gpu"
else :
    device= "cpu"

print(tensor6.device)
tensor_t=tensor6.to(device) # on gpu if available, else on cpu
print(tensor_t.device)

# New copy of tensor on cpu
tensor_x= tensor6.cpu() 

cpu
cpu


# PyTorch Tensors & NumPy conversion

In [63]:
# Numpy array to tensor
import torch
import numpy as np

array1= np.arange(0,10)
tensor1= torch.from_numpy(array1) # NOTE: Both of them share same memory
# If tensor1= torch.from_numpy(array1).type(torch.float32), then no change in the array on changing the tensor (because of reassignment)
print(array1, tensor1)

# If you want a seperate copy 
tensor2= torch.tensor(array1)
tensor2


[0 1 2 3 4 5 6 7 8 9] tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Tensors to Numpy array
array_n= tensor1.numpy() #shared memory
array_n[0]=99
print(array_n, tensor1)

# To make a seperate copy
array_m= np.array(tensor1.numpy())
array_m[0]=0
print(array_m, tensor1)



[99  1  2  3  4  5  6  7  8  9] tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])
[0 1 2 3 4 5 6 7 8 9] tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])
